### ISSUE TITLE
发现几个小问题

### ISSUE THREAD

**Issue by wxh12138** [katherineqj/DailyAccount#1]
体验了一下，大神做得好好，发现几个小问题，

更换头像时，Android 8.0 的手机不适配，会报错，“不支持裁剪功能”，

做得是真的不错，好好学习一番。

**Comment by katherineqj** [comment]
哈哈不好意思，大神不是我哦 这是我模仿改写的一个项目， 最近也是在研究实现原理，有兴趣可以一起讨论

**Comment by ELEVENEV** [comment]
拉取了你新上传的版本，各种奔溃呀，搞定了适配Android Studio 3.1.2 之后 又遭遇一个问题，不知道你是不是也有遇到这个问题？
附上报错信息
```
05-30 10:03:34.140 18255-18255/com.katherine_qj.KKMoney E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.katherine_qj.KKMoney, PID: 18255
    android.view.WindowManager$BadTokenException: Unable to add window -- token null is not valid; is your activity running?
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:765)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at com.github.johnpersano.supertoasts.ManagerSuperToast.displaySuperToast(ManagerSuperToast.java:189)
        at com.github.johnpersano.supertoasts.ManagerSuperToast.handleMessage(ManagerSuperToast.java:146)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```
